setwd("E:\\data")
x=matrix(nrow=5,ncol=10)
for (i in 1:10)
x[,i]=as.vector(runif(5)/sum(runif(5)))
x
BABA=read.csv("BABA.csv",header=TRUE,sep=",",fill=FALSE,dec=".")
CHL=read.csv("CHL.csv",header=TRUE,sep=",",fill=FALSE,dec=".")
MCB=read.csv("MCB.csv",header=TRUE,sep=",",fill=FALSE,dec=".")
PA=read.csv("pingan.csv",header=TRUE,sep=",",fill=FALSE,dec=".")
TX=read.csv("TCEHY.csv",header=TRUE,sep=",",fill=FALSE,dec=".")
####使得行列数一致
BABA=as.matrix(BABA[1:157,6])
CHL=as.matrix(CHL[1:157,6])
MCB=as.matrix(MCB[1:157,6])
PA=as.matrix(PA[1:157,6])
TX=as.matrix(TX[1:157,6])
pc=cbind(BABA,CHL,MCB,PA,TX)
###计算平均价格
M=c(mean(BABA),mean(CHL),mean(MCB),mean(PA),mean(TX))
###计算平均return
baba.r=(BABA[157,1]/BABA[1,1])^(1/(157-1))-1
chl.r=(CHL[157,1]/CHL[1,1])^(1/(157-1))-1
mcb.r=(MCB[157,1]/MCB[1,1])^(1/(157-1))-1
pa.r=(PA[157,1]/PA[1,1])^(1/(157-1))-1
tx.r=(TX[157,1]/TX[1,1])^(1/(157-1))-1
r=c(baba.r,chl.r,mcb.r,pa.r,tx.r)
####计portfolio;10个sample,每个157个数据（157*10）
p=pc%*%x
###计variance
p.v=apply(p,2,var)
###计算加权平均return
p.r=r%*%x
####查看行列数是否一致
dim(as.matrix(BABA))
dim(as.matrix(MCB))
dim(as.matrix(PA))
dim(as.matrix(TX))
dim(as.matrix(CHL))
####plot efficient frontier
vr=cbind(as.matrix(p.v),t(as.matrix(p.r)))##从小到大排列的第一步
VR=data.frame(vr)
VR=VR[order(VR$X1),]###我天，终于排序对了
plot(VR[,1],VR[,2])
lines(VR[,1],VR[,2])
